---
title: "Ecx HandIn II December.2022"
author: "Sophie Buttke"
date: "2022-12-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(estimatr)
library(dplyr)

setwd("C:/Users/sophi.LAPTOP-O5LENC3P/Desktop/R")
wage_data <- read.csv("lwage.csv")
```
a)
```{r}
reg_a <- lm_robust(lwage ~ educ + exper, data = wage_data, alpha = 0.05)
summary(reg_a)
```

b)
```{r}
reg_b <- lm_robust(lwage ~ educ + exper, data = wage_data, se_type = "HC3")
summary(reg_b)
```

c) ???
```{r}
reg_c <- lm_robust(lwage ~ educ + exper + educ*exper, data = wage_data, se_type = "HC3")
summary(reg_c)


wage_data <- wage_data %>% mutate(exper10 = exper - 10)

reg_c1 <- lm_robust(lwage ~ educ + exper + educ*exper10, data = wage_data, se_type = "HC3")
summary(reg_c1)
```

e)
```{r}
wage_data <- wage_data %>% mutate(married_urban = married*urban,
                                  nonmarried_urban = (1-married)*urban,
                                  married_rural = married*(1-urban),
                                  nonmarried_rural = (1-married)*(1-urban))

reg_e <- lm_robust(lwage ~ educ + exper + married_urban + married_rural + nonmarried_rural,
                   data = wage_data, se_type = "HC3")
summary(reg_e)
```

f)
```{r}
reg_f <- lm_robust(lwage ~ educ + exper + married + urban + meduc + feduc, data = wage_data, se_type = "HC3")
summary(reg_f)

reg_f_restricted <- lm_robust(lwage ~ educ + exper + married + urban, data = wage_data, se_type = "HC3")
summary(reg_f_restricted)
```